import { RAE } from "src/model/RAE";
import * as AT from "./mock-AT";

export const RAES: RAE[] = [
    {
        id: 1,
        description: 'Describe the main functions, strategies and design principles of operating systems, as well as their relationship with hw',
        assessmentTools:AT.RAE1
    },
    {
        id: 2,
        description: 'Compare design and implementation alternatives for the different functions of operating systems',
        assessmentTools:AT.RAE2
    },
    {
        id: 3,
        description: 'Know the problems generated by competition and explain the different mechanisms for controlling competition',
        assessmentTools:AT.RAE3
    },
    {
        id: 4,
        description: 'Use system calls to implement concurrent programs',
        assessmentTools:AT.RAE4
    },
    {
        id: 5,
        description: 'Describe the process of formulating, testing and supporting hypotheses related to the performance of concurrent programs',
        assessmentTools:AT.RAE5
    },
    {
        id: 6,
        description: 'Know tools and metrics that allow evaluating the performance of programs in an operational environment',
        assessmentTools:AT.RAE6
    }
]