import { RAE } from "src/model/RAE";
import { ASSESSMENT_TOOLS } from "./mock-AT";

export const RAES: RAE[] = [
    {
        id: 1,
        description: 'Describe the main functions, strategies and design principles of operating systems, as well as their relationship with hw',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 1)
    },
    {
        id: 2,
        description: 'Compare design and implementation alternatives for the different functions of operating systems',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 2)
    },
    {
        id: 3,
        description: 'Know the problems generated by competition and explain the different mechanisms for controlling competition',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 3)
    },
    {
        id: 4,
        description: 'Use system calls to implement concurrent programs',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 4)
    },
    {
        id: 5,
        description: 'Describe the process of formulating, testing and supporting hypotheses related to the performance of concurrent programs',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 5)
    },
    {
        id: 6,
        description: 'Know tools and metrics that allow evaluating the performance of programs in an operational environment',
        assessmentTools:ASSESSMENT_TOOLS.filter(data => data.rae == 6)
    }
]